spring:
  sql.init.mode: always
  datasource:
    url: ${DATABASE_URL_CUSTOMIZE}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
