//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.02 at 11:15:03 PM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "urn:com:tradedoubler:pf:model:xml:output",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.snaacker.sample.model.xml.output;
