//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.02 at 11:15:03 PM CEST
//

package com.snaacker.sample.model.xml.common;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.tradedoubler.pf.model.xml.common package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Sku_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "sku");
    private static final QName _Brand_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "brand");
    private static final QName _Warranty_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "warranty");
    private static final QName _Model_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "model");
    private static final QName _InStock_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "inStock");
    private static final QName _FeedId_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "feedId");
    private static final QName _ProgramName_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "programName");
    private static final QName _PromoText_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "promoText");
    private static final QName _Ean_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "ean");
    private static final QName _Manufacturer_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "manufacturer");
    private static final QName _Description_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "description");
    private static final QName _Availability_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "availability");
    private static final QName _DeliveryTime_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "deliveryTime");
    private static final QName _Isbn_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "isbn");
    private static final QName _ProductUrl_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "productUrl");
    private static final QName _TechSpecs_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "techSpecs");
    private static final QName _Name_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "name");
    private static final QName _Size_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "size");
    private static final QName _ProgramLogo_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "programLogo");
    private static final QName _Condition_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "condition");
    private static final QName _Weight_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "weight");
    private static final QName _Upc_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "upc");
    private static final QName _Mpn_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "mpn");
    private static final QName _ShortDescription_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "shortDescription");
    private static final QName _ShippingCost_QNAME =
            new QName("urn:com:tradedoubler:pf:model:xml:common", "shippingCost");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: com.tradedoubler.pf.model.xml.common
     */
    public ObjectFactory() {}

    /** Create an instance of {@link Categories } */
    public Categories createCategories() {
        return new Categories();
    }

    /** Create an instance of {@link Fields } */
    public Fields createFields() {
        return new Fields();
    }

    /** Create an instance of {@link ProductImage } */
    public ProductImage createProductImage() {
        return new ProductImage();
    }

    /** Create an instance of {@link Price } */
    public Price createPrice() {
        return new Price();
    }

    /** Create an instance of {@link Categories.Category } */
    public Categories.Category createCategoriesCategory() {
        return new Categories.Category();
    }

    /** Create an instance of {@link Fields.Field } */
    public Fields.Field createFieldsField() {
        return new Fields.Field();
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "sku")
    public JAXBElement<String> createSku(String value) {
        return new JAXBElement<String>(_Sku_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "brand")
    public JAXBElement<String> createBrand(String value) {
        return new JAXBElement<String>(_Brand_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "warranty")
    public JAXBElement<String> createWarranty(String value) {
        return new JAXBElement<String>(_Warranty_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "inStock")
    public JAXBElement<Integer> createInStock(Integer value) {
        return new JAXBElement<Integer>(_InStock_QNAME, Integer.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "feedId")
    public JAXBElement<Long> createFeedId(Long value) {
        return new JAXBElement<Long>(_FeedId_QNAME, Long.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "programName")
    public JAXBElement<String> createProgramName(String value) {
        return new JAXBElement<String>(_ProgramName_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "promoText")
    public JAXBElement<String> createPromoText(String value) {
        return new JAXBElement<String>(_PromoText_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "ean")
    public JAXBElement<String> createEan(String value) {
        return new JAXBElement<String>(_Ean_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "manufacturer")
    public JAXBElement<String> createManufacturer(String value) {
        return new JAXBElement<String>(_Manufacturer_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "availability")
    public JAXBElement<String> createAvailability(String value) {
        return new JAXBElement<String>(_Availability_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "deliveryTime")
    public JAXBElement<String> createDeliveryTime(String value) {
        return new JAXBElement<String>(_DeliveryTime_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "isbn")
    public JAXBElement<String> createIsbn(String value) {
        return new JAXBElement<String>(_Isbn_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "productUrl")
    public JAXBElement<String> createProductUrl(String value) {
        return new JAXBElement<String>(_ProductUrl_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "techSpecs")
    public JAXBElement<String> createTechSpecs(String value) {
        return new JAXBElement<String>(_TechSpecs_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "size")
    public JAXBElement<String> createSize(String value) {
        return new JAXBElement<String>(_Size_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "programLogo")
    public JAXBElement<String> createProgramLogo(String value) {
        return new JAXBElement<String>(_ProgramLogo_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "condition")
    public JAXBElement<String> createCondition(String value) {
        return new JAXBElement<String>(_Condition_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "weight")
    public JAXBElement<String> createWeight(String value) {
        return new JAXBElement<String>(_Weight_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "upc")
    public JAXBElement<String> createUpc(String value) {
        return new JAXBElement<String>(_Upc_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "mpn")
    public JAXBElement<String> createMpn(String value) {
        return new JAXBElement<String>(_Mpn_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(
            namespace = "urn:com:tradedoubler:pf:model:xml:common",
            name = "shortDescription")
    public JAXBElement<String> createShortDescription(String value) {
        return new JAXBElement<String>(_ShortDescription_QNAME, String.class, null, value);
    }

    /** Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}} */
    @XmlElementDecl(namespace = "urn:com:tradedoubler:pf:model:xml:common", name = "shippingCost")
    public JAXBElement<String> createShippingCost(String value) {
        return new JAXBElement<String>(_ShippingCost_QNAME, String.class, null, value);
    }
}
