//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.02 at 11:15:03 PM CEST
//

package com.snaacker.sample.model.xml.common;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "",
        propOrder = {"value"})
@XmlRootElement(name = "productImage")
public class ProductImage {

    @XmlValue protected String value;

    @XmlAttribute(name = "height", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short height;

    @XmlAttribute(name = "width", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short width;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /** Gets the value of the height property. */
    public short getHeight() {
        return height;
    }

    /** Sets the value of the height property. */
    public void setHeight(short value) {
        this.height = value;
    }

    /** Gets the value of the width property. */
    public short getWidth() {
        return width;
    }

    /** Sets the value of the width property. */
    public void setWidth(short value) {
        this.width = value;
    }
}
